# loglevel: DEBUG
loglevel: INFO
# linkDir is a Dir in your PATH where a sysmbolic link to tthe tool is created
linkDir: !ENV ${HOME}/.local/bin
# installDir is the location where the different versions of the tool are installed
installDir: !ENV ${HOME}/cliTools
toolsToInstall:
- goml
- kubebuilder
- kubectl
- spruce
- yq
- kubectx
- kubens
- kind
- aviator
- calicoctl
- kn
- spotdl
- hey
- crane
- golangci-lint
- k9s
- dyff
- fly
- helm
- havener
- retry
- stern
- kubectl-neat
- ko
- yft
- pack
- tsh
- teleport
- tctl
- gosec
- marp
- bw