toolMode: production
fileFilter: "*.jpeg"
#toolOptions: (preserveDirStructure|flat)
toolOptions: preserveDirStructure
incrementMinutes: 5
dayoffsethours: 1
# Directories
develop:
  srcDirName: "testdata/src"
production:
  srcDirName: "/home/zinks/Photos_unsorted/WhatsAppImages/"
tgtDirName: "/home/zinks/Photos_unsorted/WhatsAppImagesConverted/"
