# loglevel: DEBUG
loglevel: INFO
srcRootDir: !ENV ${HOME}/workspace/testdata_myprg/SymlinkFavoriten 
srcRelativeDirName: FamilienVideos/Favoriten-Familie-Zink-Videos
tgtDirName: !ENV ${HOME}/workspace/workspace/src/github.com/zinkst/MyPythonProgs/ShrinkVideoFavorites/testdata
searchExtension: [mkv, mp4, mpeg]
# searchExtension: [mp4, mpeg]
