loglevel: INFO
photos:
  # use production or develop config
  configuration: develop
  # create hardlinks or soft links
  # valid values [ hard , soft ]
  linkType: soft
  # valid values [ relative , absolute ] create relative path links
  linkTarget: relative
  # extension of files which are used in search (case insensitive)
  searchExtension: [jpg, jpeg, png]
  develop:
    # directory where files are from which the originals are to be searched
    SRC-ROOT-DIR: /home/zinks/workspace/src/github.com/zinkst/MyPythonProgs/SymlinkFavoriten/testData
    FAVORITES-SRC-DIR: Photos/Favoriten/Compressed
    # Target Directory where symlinks are stored
    TGT-ROOT-DIR: /home/zinks/workspace/src/github.com/zinkst/MyPythonProgs/SymlinkFavoriten/testData
    FAVORITES-TGT-DIR: tgt/Favoriten
    NOTFOUND_FILES_TGT_DIR: tgt/NotFoundFiles
    # directories where Originale are searched
    ORIGINALS-DIRS: 
        - Photos/Sammlung
    SIMULATE: false
  production:
    # directory where files are from which the originals are to be searched
    SRC-ROOT-DIR: /links/Photos
    FAVORITES-SRC-DIR: "Favoriten/Compressed/Familie Zink"
    # Target Directory where symlinks are stored
    TGT-ROOT-DIR: /links/Photos
    FAVORITES-TGT-DIR: "Favoriten/Symlinks/Familie Zink"
    NOTFOUND_FILES_TGT_DIR: Favoriten/Symlinks/NotFoundFiles
    # directories where Originale are searched
    ORIGINALS-DIRS: 
        - Sammlung
    SIMULATE: false
videos:
  # use production or develop config
  configuration: develop
  # create hardlinks or soft links
  # valid values [ hard , soft ]
  linkType: soft
  # valid values [ relative , absolute ] create relative path links
  linkTarget: relative
  # extension of files which are used in search (case insensitive)
  searchExtension: [mkv, mp4, mpeg]
  develop:
    # directory where files are from which the originals are to be searched
    SRC-ROOT-DIR: /home/zinks/workspace/src/github.com/zinkst/MyPythonProgs/SymlinkFavoriten/testData
    FAVORITES-SRC-DIR: Photos/Favoriten/Compressed
    # Target Directory where symlinks are stored
    TGT-ROOT-DIR: /home/zinks/workspace/src/github.com/zinkst/MyPythonProgs/SymlinkFavoriten/testData
    FAVORITES-TGT-DIR: tgt/Favoriten
    NOTFOUND_FILES_TGT_DIR: tgt/NotFoundFiles
    # directories where Originale are searched
    ORIGINALS-DIRS: 
        - Photos/Sammlung
    SIMULATE: false
  production:
    # directory where files are from which the originals are to be searched
    SRC-ROOT-DIR: /links/Photos
    FAVORITES-SRC-DIR: "Favoriten/Compressed/Familie Zink"
    # Target Directory where symlinks are stored
    TGT-ROOT-DIR: /links/Photos
    FAVORITES-TGT-DIR: "Favoriten/Symlinks/Familie Zink"
    NOTFOUND_FILES_TGT_DIR: Favoriten/Symlinks/NotFoundFiles
    # directories where Originale are searched
    ORIGINALS-DIRS: 
        - Sammlung
    SIMULATE: false
