toolMode: develop
fileFilter: "*.jpg"
#toolOptions: (preserveDirStructure|flat)
toolOptions: flat
incrementMinutes: 15
dayoffsethours: 7
# Directories
develop:
  srcDirName: "testdata/src"
production:
  srcDirName: "/home/zinks/Photos_unsorted/1997 Neuseeland 11.12.96 - 1.2.97"
tgtDirName: "/home/zinks/Photos_unsorted/IncrementExifTimeStamp"
