toolMode: develop
fileFilter: "*.jpeg"
#toolOptions: (preserveDirStructure|flat)
toolOptions: preserveDirStructure
incrementMinutes: 5
dayoffsethours: 1
# Directories
develop:
  srcDirName: "testdata/src"
production:
  srcDirName: "/home/zinks/Photos_unsorted/2000 Westküste Amerika 22.7. - 1.10"
tgtDirName: "/home/zinks/Photos_unsorted/IncrementExifTimeStamp"
