# use production or development config
configuration: production
# create hardlinks or soft links
# valid values [ hard , soft ]
linkType: soft
loglevel: INFO
# extension of files which are used in search (case insensitive)
searchExtension: [jpg, jpeg]
develop:
    # directory where files are from which the originals are to be searched
    FAVORITES-SRC-DIR: Photos/Converted
    FAVORITES-TGT-DIR: tgt/Favoriten
    NOTFOUND_FILES_TGT_DIR: tgt/NotFoundFiles
    # directories where Originale are searched
    ORIGINALS-DIRS: 
        - Photos/Sammlung
    SRC-ROOT-DIR: /home/zinks/workspace/src/github.com/zinkst/MyPythonProgs/SymlinkPhotoFavoriten/testData
    TGT-ROOT-DIR: /home/zinks/workspace/src/github.com/zinkst/MyPythonProgs/SymlinkPhotoFavoriten/testData
    SIMULATE: false
production:
    FAVORITES-SRC-DIR: "Favoriten/Compressed/Familie Zink/2024"
    FAVORITES-TGT-DIR: "Favoriten/Symlinks/2024"
    NOTFOUND_FILES_TGT_DIR: Favoriten/Symlinks/NotFoundFiles
    # directories where Originale are searched
    ORIGINALS-DIRS: 
        - Sammlung/2024
    SRC-ROOT-DIR: /links/Photos
    TGT-ROOT-DIR: /links/Photos
    SIMULATE: false
